language: node

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
  - yarn

scripts:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  keep_history: true
  on:
    branch: main

local_dir: ./docs/.vuepress/dist
